### ISSUE TITLE
Messages for web has a new URL

### ISSUE THREAD

**Issue by johnmmcgee** [kelyvin/Android-Messages-For-Desktop#14]
It appears that the URL has changed for the messages.  Therefor the app no longer functions as expected.

<img width="1087" alt="Screen Shot 2019-04-02 at 3 04 41 PM" src="https://user-images.githubusercontent.com/32335296/55429125-b5f92d80-5558-11e9-891b-64506bec0fc7.png">

**Comment by adyavanapalli** [comment]
@johnmmcgee 
Assuming you're running on MacOS, trying changing the `"targetUrl"` path to `"https://messages.google.com/"` in the following file:
Android-Messages-For-Desktop/Mac/Android Messages.app/Contents/Resources/app/nativefier.json

**Comment by Pardlerum** [comment]
On Windows the same edit goes in:
<installed folder>/resources/app/nativefier.json

Make sure you kill the existing process to re-load the changed config...

**Comment by kelyvin** [comment]
Thanks @johnmmcgee for bringing this to my attention and thanks everyone else for workaround solutions. I have updated the releases with the latest URL versions, which you can find here: 

https://github.com/kelyvin/Android-Messages-For-Desktop/releases/tag/v1.1.0

Thanks!

**Comment by atentis** [comment]
It's also no longer called Android Messages. 

It's Messages by Google / Google Messages

**Comment by kelyvin** [comment]
Thanks for letting me know, I will slowly start updating everything with the new name.
