### ISSUE TITLE
Tray version doesn't close to system tray.

### ISSUE THREAD

**Issue by poweruser667** [kelyvin/Android-Messages-For-Desktop#15]
Using Windows 10 Pro x64, I've extracted the tray version and it seems to run fine but it doesn't close to the system tray like it's supposed to.

**Comment by dplautjhmi** [comment]
Same problem. It would be great if it closed to app. One less icon on my task bar.

**Comment by pbanj** [comment]
same issue. i even tried the normal one to see if maybe they got mixed up

**Comment by pbanj** [comment]
i figured out a fix

go to `\Android Messages (tray)\resources\app` and edit the `nativefier.json` file. look for `"tray":` and change it from false to true. you can do this on the non tray version also and it will have the proper icons and stay in the tray when you close it.
