### ISSUE TITLE
Run on Startup

### ISSUE THREAD

**Issue by drew5494** [kelyvin/Android-Messages-For-Desktop#4]
Hey great idea with this app!  Is there any way I can run it in the background on startup on my Mac like the iMessage app for Mac?
Thanks!

**Comment by tpitts13** [comment]
If you go to the System Preferences > Users and Groups pane in Mac OS you can add startup apps.

![image](https://user-images.githubusercontent.com/4387274/42051236-a9d48358-7ac8-11e8-8313-297b2936e8bc.png)
