### ISSUE TITLE
Ubuntu shortcut for the launcher / dock

### ISSUE THREAD

**Issue by FlorentLM** [kelyvin/Android-Messages-For-Desktop#8]
Hey,
Here is a simple shortcut for those of you who wish to have the app in your launcher and/or favorites.

Create and open the shortcut file
```
nano ~/.local/share/applications/Android-Messages.desktop
```
Put this inside
```ini
[Desktop Entry]
Version=1.0.0
Name=Android Messages
Comment=Send and recieve messages from your Android Phone
Keywords=Message;Messaging;Android;SMS
Exec=/path/to/installfolder/android-messages
Icon=/path/to/installfolder/resources/app/icon.png
Terminal=false
Type=Application
Categories=Internet;Application;
StartupWMClass=android-messages-nativefier-f3cfa3
```

Be sure to replace `/path/to/installfolder/` with your actual installation folder

Android Messages should appear along your other native apps

**Comment by kelyvin** [comment]
Thanks for this! I have included the instructions in the README
