### ISSUE TITLE
Sign "Android Messages" app

### ISSUE THREAD

**Issue by rhuddleston** [kelyvin/Android-Messages-For-Desktop#9]
It would be really helpful to sign the app that is available messagesfordesktop.com so that people can install this easily in environments that require all apps to be signed.

**Comment by kelyvin** [comment]
I would love to, but signing would require me to pay for both Apple's developer program and a Windows signing certificate. I currently do not have a direct income stream so I will not be doing that right now, sorry :(

**Comment by rhuddleston** [comment]
https://developer.apple.com/support/membership-fee-waiver/
